### Check all users / employees

GET http://localhost:3000/users

### Check one user / employee

GET http://localhost:3000/users/2

### Create a user / employee

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
   "name": "Fundi",
   "age": 23,
   "sex": "Female",
   "title":"CTO",
   "department":"IT Solutions",
   "employment_type":"Contract",
   "email":"zah@gmail.com",
   "password":"1234456"
}

### FInd a particular user with ID

GET http://localhost:3000/auth/3


### Find all users with a particular email

GET http://localhost:3000/auth?email=yma@gmail.com