### Check all users / employees

GET http://localhost:3000/users

### Check one user / employee

GET http://localhost:3000/users/2

### Create a user / employee

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
   "id": 1,
   "name": "Yannick Zahinda",
   "sex": "Male",
   "age": 24,
   "title":"Software Developer",
   "department":"IT Services",
   "employment_type":"Full time",
   "email":"ymulikuza@gmail.com",
   "password":"Naruto$$0511!"
}